# Generated by Django 3.1.4 on 2021-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('characteristic', models.CharField(max_length=300, verbose_name='Характеристика')),
                ('amount', models.IntegerField(default=0, verbose_name='Кількість')),
                ('placing', models.CharField(max_length=150, verbose_name='Розміщення')),
                ('producer', models.CharField(max_length=100, verbose_name='Виробник')),
                ('valid_until', models.DateTimeField(verbose_name='Дійсний до')),
                ('field_of_use', models.CharField(max_length=150, verbose_name='Галузь використання')),
                ('provider', models.CharField(max_length=100, verbose_name='Постачальник')),
            ],
            options={
                'verbose_name': 'Реагент/Матеріал',
                'verbose_name_plural': 'Реагентти/Матеріали',
            },
        ),
    ]
