version: '3.8'

services:
  management_back:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file:
      - ./.env.prod
    depends_on:
      - management-db
  management-db:
    image: postgres:12.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
    - static_volume:/usr/src/app/staticfiles
    - media_volume:/usr/src/app/media
    depends_on:
      - management_back

volumes:
  postgres_data:
  static_volume:
  media_volume: