version: '3.8'

services:
  management_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  management-db:
    image: postgres:12.5
    volumes:
      - management_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=management_user
      - POSTGRES_PASSWORD=management_pass
      - POSTGRES_DB=management_dev

volumes:
  management_postgres_data: