# Generated by Django 3.1.4 on 2021-02-18 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Назва')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('description', models.TextField(max_length=1000, verbose_name='Короткий опис')),
                ('category', models.CharField(choices=[('Teaching', 'Навчання'), ('Science', 'Наука'), ('Business', 'Бізнес')], default='Teaching', max_length=8, verbose_name='Категорія')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('performers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Виконавці')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекти',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата створення')),
                ('deadline', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дедлайн')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_worker', to=settings.AUTH_USER_MODEL, verbose_name='Виконавець')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Завдання',
                'verbose_name_plural': 'Завдання',
            },
        ),
        migrations.CreateModel(
            name='TimeFixation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('begin', models.TimeField(auto_now_add=True, verbose_name='Початок')),
                ('end', models.TimeField(blank=True, null=True, verbose_name='Кінець')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Тривалість')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timer_fixations', to='projects.task', verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Фіксація часу',
                'verbose_name_plural': 'Фіксації часу',
            },
        ),
    ]
