# Generated by Django 3.1.4 on 2021-06-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210612_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timefixation',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='timefixation',
            name='end',
        ),
    ]
