# Generated by Django 3.1.4 on 2021-06-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201229_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.worker', verbose_name='Працівник')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
            ],
        ),
    ]
