# Generated by Django 3.1.4 on 2021-06-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Зарплата', 'verbose_name_plural': 'Зарплати'},
        ),
    ]
